/*
 * Conductor API Server
 *
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SearchResultWorkflowSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchResultWorkflowSummaryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchResultWorkflowSummary
        //private SearchResultWorkflowSummary instance;

        public SearchResultWorkflowSummaryTests()
        {
            // TODO uncomment below to create an instance of SearchResultWorkflowSummary
            //instance = new SearchResultWorkflowSummary();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchResultWorkflowSummary
        /// </summary>
        [Fact]
        public void SearchResultWorkflowSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchResultWorkflowSummary
            //Assert.IsType<SearchResultWorkflowSummary>(instance);
        }


        /// <summary>
        /// Test the property 'TotalHits'
        /// </summary>
        [Fact]
        public void TotalHitsTest()
        {
            // TODO unit test for the property 'TotalHits'
        }
        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Fact]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }

    }

}
