/*
 * Conductor API Server
 *
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing TaskDef
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TaskDefTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TaskDef
        //private TaskDef instance;

        public TaskDefTests()
        {
            // TODO uncomment below to create an instance of TaskDef
            //instance = new TaskDef();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TaskDef
        /// </summary>
        [Fact]
        public void TaskDefInstanceTest()
        {
            // TODO uncomment below to test "IsType" TaskDef
            //Assert.IsType<TaskDef>(instance);
        }


        /// <summary>
        /// Test the property 'OwnerApp'
        /// </summary>
        [Fact]
        public void OwnerAppTest()
        {
            // TODO unit test for the property 'OwnerApp'
        }
        /// <summary>
        /// Test the property 'CreateTime'
        /// </summary>
        [Fact]
        public void CreateTimeTest()
        {
            // TODO unit test for the property 'CreateTime'
        }
        /// <summary>
        /// Test the property 'UpdateTime'
        /// </summary>
        [Fact]
        public void UpdateTimeTest()
        {
            // TODO unit test for the property 'UpdateTime'
        }
        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Fact]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }
        /// <summary>
        /// Test the property 'UpdatedBy'
        /// </summary>
        [Fact]
        public void UpdatedByTest()
        {
            // TODO unit test for the property 'UpdatedBy'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'RetryCount'
        /// </summary>
        [Fact]
        public void RetryCountTest()
        {
            // TODO unit test for the property 'RetryCount'
        }
        /// <summary>
        /// Test the property 'TimeoutSeconds'
        /// </summary>
        [Fact]
        public void TimeoutSecondsTest()
        {
            // TODO unit test for the property 'TimeoutSeconds'
        }
        /// <summary>
        /// Test the property 'InputKeys'
        /// </summary>
        [Fact]
        public void InputKeysTest()
        {
            // TODO unit test for the property 'InputKeys'
        }
        /// <summary>
        /// Test the property 'OutputKeys'
        /// </summary>
        [Fact]
        public void OutputKeysTest()
        {
            // TODO unit test for the property 'OutputKeys'
        }
        /// <summary>
        /// Test the property 'TimeoutPolicy'
        /// </summary>
        [Fact]
        public void TimeoutPolicyTest()
        {
            // TODO unit test for the property 'TimeoutPolicy'
        }
        /// <summary>
        /// Test the property 'RetryLogic'
        /// </summary>
        [Fact]
        public void RetryLogicTest()
        {
            // TODO unit test for the property 'RetryLogic'
        }
        /// <summary>
        /// Test the property 'RetryDelaySeconds'
        /// </summary>
        [Fact]
        public void RetryDelaySecondsTest()
        {
            // TODO unit test for the property 'RetryDelaySeconds'
        }
        /// <summary>
        /// Test the property 'ResponseTimeoutSeconds'
        /// </summary>
        [Fact]
        public void ResponseTimeoutSecondsTest()
        {
            // TODO unit test for the property 'ResponseTimeoutSeconds'
        }
        /// <summary>
        /// Test the property 'ConcurrentExecLimit'
        /// </summary>
        [Fact]
        public void ConcurrentExecLimitTest()
        {
            // TODO unit test for the property 'ConcurrentExecLimit'
        }
        /// <summary>
        /// Test the property 'InputTemplate'
        /// </summary>
        [Fact]
        public void InputTemplateTest()
        {
            // TODO unit test for the property 'InputTemplate'
        }
        /// <summary>
        /// Test the property 'RateLimitPerFrequency'
        /// </summary>
        [Fact]
        public void RateLimitPerFrequencyTest()
        {
            // TODO unit test for the property 'RateLimitPerFrequency'
        }
        /// <summary>
        /// Test the property 'RateLimitFrequencyInSeconds'
        /// </summary>
        [Fact]
        public void RateLimitFrequencyInSecondsTest()
        {
            // TODO unit test for the property 'RateLimitFrequencyInSeconds'
        }
        /// <summary>
        /// Test the property 'IsolationGroupId'
        /// </summary>
        [Fact]
        public void IsolationGroupIdTest()
        {
            // TODO unit test for the property 'IsolationGroupId'
        }
        /// <summary>
        /// Test the property 'ExecutionNameSpace'
        /// </summary>
        [Fact]
        public void ExecutionNameSpaceTest()
        {
            // TODO unit test for the property 'ExecutionNameSpace'
        }
        /// <summary>
        /// Test the property 'OwnerEmail'
        /// </summary>
        [Fact]
        public void OwnerEmailTest()
        {
            // TODO unit test for the property 'OwnerEmail'
        }
        /// <summary>
        /// Test the property 'PollTimeoutSeconds'
        /// </summary>
        [Fact]
        public void PollTimeoutSecondsTest()
        {
            // TODO unit test for the property 'PollTimeoutSeconds'
        }
        /// <summary>
        /// Test the property 'BackoffScaleFactor'
        /// </summary>
        [Fact]
        public void BackoffScaleFactorTest()
        {
            // TODO unit test for the property 'BackoffScaleFactor'
        }

    }

}
