/*
 * Conductor API Server
 *
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing WorkflowDef
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WorkflowDefTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WorkflowDef
        //private WorkflowDef instance;

        public WorkflowDefTests()
        {
            // TODO uncomment below to create an instance of WorkflowDef
            //instance = new WorkflowDef();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WorkflowDef
        /// </summary>
        [Fact]
        public void WorkflowDefInstanceTest()
        {
            // TODO uncomment below to test "IsType" WorkflowDef
            //Assert.IsType<WorkflowDef>(instance);
        }


        /// <summary>
        /// Test the property 'OwnerApp'
        /// </summary>
        [Fact]
        public void OwnerAppTest()
        {
            // TODO unit test for the property 'OwnerApp'
        }
        /// <summary>
        /// Test the property 'CreateTime'
        /// </summary>
        [Fact]
        public void CreateTimeTest()
        {
            // TODO unit test for the property 'CreateTime'
        }
        /// <summary>
        /// Test the property 'UpdateTime'
        /// </summary>
        [Fact]
        public void UpdateTimeTest()
        {
            // TODO unit test for the property 'UpdateTime'
        }
        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Fact]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }
        /// <summary>
        /// Test the property 'UpdatedBy'
        /// </summary>
        [Fact]
        public void UpdatedByTest()
        {
            // TODO unit test for the property 'UpdatedBy'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property '_Version'
        /// </summary>
        [Fact]
        public void _VersionTest()
        {
            // TODO unit test for the property '_Version'
        }
        /// <summary>
        /// Test the property 'Tasks'
        /// </summary>
        [Fact]
        public void TasksTest()
        {
            // TODO unit test for the property 'Tasks'
        }
        /// <summary>
        /// Test the property 'InputParameters'
        /// </summary>
        [Fact]
        public void InputParametersTest()
        {
            // TODO unit test for the property 'InputParameters'
        }
        /// <summary>
        /// Test the property 'OutputParameters'
        /// </summary>
        [Fact]
        public void OutputParametersTest()
        {
            // TODO unit test for the property 'OutputParameters'
        }
        /// <summary>
        /// Test the property 'FailureWorkflow'
        /// </summary>
        [Fact]
        public void FailureWorkflowTest()
        {
            // TODO unit test for the property 'FailureWorkflow'
        }
        /// <summary>
        /// Test the property 'SchemaVersion'
        /// </summary>
        [Fact]
        public void SchemaVersionTest()
        {
            // TODO unit test for the property 'SchemaVersion'
        }
        /// <summary>
        /// Test the property 'Restartable'
        /// </summary>
        [Fact]
        public void RestartableTest()
        {
            // TODO unit test for the property 'Restartable'
        }
        /// <summary>
        /// Test the property 'WorkflowStatusListenerEnabled'
        /// </summary>
        [Fact]
        public void WorkflowStatusListenerEnabledTest()
        {
            // TODO unit test for the property 'WorkflowStatusListenerEnabled'
        }
        /// <summary>
        /// Test the property 'OwnerEmail'
        /// </summary>
        [Fact]
        public void OwnerEmailTest()
        {
            // TODO unit test for the property 'OwnerEmail'
        }
        /// <summary>
        /// Test the property 'TimeoutPolicy'
        /// </summary>
        [Fact]
        public void TimeoutPolicyTest()
        {
            // TODO unit test for the property 'TimeoutPolicy'
        }
        /// <summary>
        /// Test the property 'TimeoutSeconds'
        /// </summary>
        [Fact]
        public void TimeoutSecondsTest()
        {
            // TODO unit test for the property 'TimeoutSeconds'
        }
        /// <summary>
        /// Test the property 'Variables'
        /// </summary>
        [Fact]
        public void VariablesTest()
        {
            // TODO unit test for the property 'Variables'
        }
        /// <summary>
        /// Test the property 'InputTemplate'
        /// </summary>
        [Fact]
        public void InputTemplateTest()
        {
            // TODO unit test for the property 'InputTemplate'
        }

    }

}
