/*
 * Conductor API Server
 *
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing MetadataResourceApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class MetadataResourceApiTests : IDisposable
    {
        private MetadataResourceApi instance;

        public MetadataResourceApiTests()
        {
            instance = new MetadataResourceApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MetadataResourceApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' MetadataResourceApi
            //Assert.IsType<MetadataResourceApi>(instance);
        }

        /// <summary>
        /// Test Create
        /// </summary>
        [Fact]
        public void CreateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WorkflowDef workflowDef = null;
            //instance.Create(workflowDef);
        }

        /// <summary>
        /// Test Get
        /// </summary>
        [Fact]
        public void GetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //int? version = null;
            //var response = instance.Get(name, version);
            //Assert.IsType<WorkflowDef>(response);
        }

        /// <summary>
        /// Test GetAllWorkflows
        /// </summary>
        [Fact]
        public void GetAllWorkflowsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string access = null;
            //var response = instance.GetAllWorkflows(access);
            //Assert.IsType<List<WorkflowDef>>(response);
        }

        /// <summary>
        /// Test GetTaskDef
        /// </summary>
        [Fact]
        public void GetTaskDefTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tasktype = null;
            //var response = instance.GetTaskDef(tasktype);
            //Assert.IsType<TaskDef>(response);
        }

        /// <summary>
        /// Test GetTaskDefs
        /// </summary>
        [Fact]
        public void GetTaskDefsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string access = null;
            //var response = instance.GetTaskDefs(access);
            //Assert.IsType<List<TaskDef>>(response);
        }

        /// <summary>
        /// Test RegisterTaskDef
        /// </summary>
        [Fact]
        public void RegisterTaskDefTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<TaskDef> taskDef = null;
            //instance.RegisterTaskDef(taskDef);
        }

        /// <summary>
        /// Test UnregisterTaskDef
        /// </summary>
        [Fact]
        public void UnregisterTaskDefTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tasktype = null;
            //instance.UnregisterTaskDef(tasktype);
        }

        /// <summary>
        /// Test UnregisterWorkflowDef
        /// </summary>
        [Fact]
        public void UnregisterWorkflowDefTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //int version = null;
            //instance.UnregisterWorkflowDef(name, version);
        }

        /// <summary>
        /// Test Update1
        /// </summary>
        [Fact]
        public void Update1Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<WorkflowDef> workflowDef = null;
            //instance.Update1(workflowDef);
        }

        /// <summary>
        /// Test UpdateTaskDef
        /// </summary>
        [Fact]
        public void UpdateTaskDefTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //TaskDef taskDef = null;
            //instance.UpdateTaskDef(taskDef);
        }
    }
}
