/* 
 * Orkes Conductor API Server
 *
 * Orkes Conductor API Server
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Action
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ActionTests
    {
        // TODO uncomment below to declare an instance variable for Action
        //private Action instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Action
            //instance = new Action();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Action
        /// </summary>
        [Test]
        public void ActionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Action
            //Assert.IsInstanceOfType<Action> (instance, "variable 'instance' is a Action");
        }


        /// <summary>
        /// Test the property '_Action'
        /// </summary>
        [Test]
        public void _ActionTest()
        {
            // TODO unit test for the property '_Action'
        }
        /// <summary>
        /// Test the property 'CompleteTask'
        /// </summary>
        [Test]
        public void CompleteTaskTest()
        {
            // TODO unit test for the property 'CompleteTask'
        }
        /// <summary>
        /// Test the property 'ExpandInlineJSON'
        /// </summary>
        [Test]
        public void ExpandInlineJSONTest()
        {
            // TODO unit test for the property 'ExpandInlineJSON'
        }
        /// <summary>
        /// Test the property 'FailTask'
        /// </summary>
        [Test]
        public void FailTaskTest()
        {
            // TODO unit test for the property 'FailTask'
        }
        /// <summary>
        /// Test the property 'StartWorkflow'
        /// </summary>
        [Test]
        public void StartWorkflowTest()
        {
            // TODO unit test for the property 'StartWorkflow'
        }
        /// <summary>
        /// Test the property 'TerminateWorkflow'
        /// </summary>
        [Test]
        public void TerminateWorkflowTest()
        {
            // TODO unit test for the property 'TerminateWorkflow'
        }
        /// <summary>
        /// Test the property 'UpdateWorkflowVariables'
        /// </summary>
        [Test]
        public void UpdateWorkflowVariablesTest()
        {
            // TODO unit test for the property 'UpdateWorkflowVariables'
        }

    }

}
