/* 
 * Orkes Conductor API Server
 *
 * Orkes Conductor API Server
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AuthorizationRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AuthorizationRequestTests
    {
        // TODO uncomment below to declare an instance variable for AuthorizationRequest
        //private AuthorizationRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AuthorizationRequest
            //instance = new AuthorizationRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AuthorizationRequest
        /// </summary>
        [Test]
        public void AuthorizationRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AuthorizationRequest
            //Assert.IsInstanceOfType<AuthorizationRequest> (instance, "variable 'instance' is a AuthorizationRequest");
        }


        /// <summary>
        /// Test the property 'Access'
        /// </summary>
        [Test]
        public void AccessTest()
        {
            // TODO unit test for the property 'Access'
        }
        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Test]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
        /// <summary>
        /// Test the property 'Target'
        /// </summary>
        [Test]
        public void TargetTest()
        {
            // TODO unit test for the property 'Target'
        }

    }

}
