/* 
 * Orkes Conductor API Server
 *
 * Orkes Conductor API Server
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BulkResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BulkResponseTests
    {
        // TODO uncomment below to declare an instance variable for BulkResponse
        //private BulkResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BulkResponse
            //instance = new BulkResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BulkResponse
        /// </summary>
        [Test]
        public void BulkResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BulkResponse
            //Assert.IsInstanceOfType<BulkResponse> (instance, "variable 'instance' is a BulkResponse");
        }


        /// <summary>
        /// Test the property 'BulkErrorResults'
        /// </summary>
        [Test]
        public void BulkErrorResultsTest()
        {
            // TODO unit test for the property 'BulkErrorResults'
        }
        /// <summary>
        /// Test the property 'BulkSuccessfulResults'
        /// </summary>
        [Test]
        public void BulkSuccessfulResultsTest()
        {
            // TODO unit test for the property 'BulkSuccessfulResults'
        }

    }

}
