/* 
 * Orkes Conductor API Server
 *
 * Orkes Conductor API Server
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ScrollableSearchResultWorkflowSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ScrollableSearchResultWorkflowSummaryTests
    {
        // TODO uncomment below to declare an instance variable for ScrollableSearchResultWorkflowSummary
        //private ScrollableSearchResultWorkflowSummary instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ScrollableSearchResultWorkflowSummary
            //instance = new ScrollableSearchResultWorkflowSummary();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ScrollableSearchResultWorkflowSummary
        /// </summary>
        [Test]
        public void ScrollableSearchResultWorkflowSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ScrollableSearchResultWorkflowSummary
            //Assert.IsInstanceOfType<ScrollableSearchResultWorkflowSummary> (instance, "variable 'instance' is a ScrollableSearchResultWorkflowSummary");
        }


        /// <summary>
        /// Test the property 'QueryId'
        /// </summary>
        [Test]
        public void QueryIdTest()
        {
            // TODO unit test for the property 'QueryId'
        }
        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Test]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }

    }

}
