/* 
 * Orkes Conductor API Server
 *
 * Orkes Conductor API Server
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SearchResultTask
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SearchResultTaskTests
    {
        // TODO uncomment below to declare an instance variable for SearchResultTask
        //private SearchResultTask instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SearchResultTask
            //instance = new SearchResultTask();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SearchResultTask
        /// </summary>
        [Test]
        public void SearchResultTaskInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SearchResultTask
            //Assert.IsInstanceOfType<SearchResultTask> (instance, "variable 'instance' is a SearchResultTask");
        }


        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Test]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }
        /// <summary>
        /// Test the property 'TotalHits'
        /// </summary>
        [Test]
        public void TotalHitsTest()
        {
            // TODO unit test for the property 'TotalHits'
        }

    }

}
