/* 
 * Orkes Conductor API Server
 *
 * Orkes Conductor API Server
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TaskDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TaskDetailsTests
    {
        // TODO uncomment below to declare an instance variable for TaskDetails
        //private TaskDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TaskDetails
            //instance = new TaskDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TaskDetails
        /// </summary>
        [Test]
        public void TaskDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TaskDetails
            //Assert.IsInstanceOfType<TaskDetails> (instance, "variable 'instance' is a TaskDetails");
        }


        /// <summary>
        /// Test the property 'Output'
        /// </summary>
        [Test]
        public void OutputTest()
        {
            // TODO unit test for the property 'Output'
        }
        /// <summary>
        /// Test the property 'TaskId'
        /// </summary>
        [Test]
        public void TaskIdTest()
        {
            // TODO unit test for the property 'TaskId'
        }
        /// <summary>
        /// Test the property 'TaskRefName'
        /// </summary>
        [Test]
        public void TaskRefNameTest()
        {
            // TODO unit test for the property 'TaskRefName'
        }
        /// <summary>
        /// Test the property 'WorkflowId'
        /// </summary>
        [Test]
        public void WorkflowIdTest()
        {
            // TODO unit test for the property 'WorkflowId'
        }

    }

}
