/* 
 * Orkes Conductor API Server
 *
 * Orkes Conductor API Server
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WebhookExecutionHistory
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WebhookExecutionHistoryTests
    {
        // TODO uncomment below to declare an instance variable for WebhookExecutionHistory
        //private WebhookExecutionHistory instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WebhookExecutionHistory
            //instance = new WebhookExecutionHistory();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WebhookExecutionHistory
        /// </summary>
        [Test]
        public void WebhookExecutionHistoryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WebhookExecutionHistory
            //Assert.IsInstanceOfType<WebhookExecutionHistory> (instance, "variable 'instance' is a WebhookExecutionHistory");
        }


        /// <summary>
        /// Test the property 'EventId'
        /// </summary>
        [Test]
        public void EventIdTest()
        {
            // TODO unit test for the property 'EventId'
        }
        /// <summary>
        /// Test the property 'Matched'
        /// </summary>
        [Test]
        public void MatchedTest()
        {
            // TODO unit test for the property 'Matched'
        }
        /// <summary>
        /// Test the property 'TimeStamp'
        /// </summary>
        [Test]
        public void TimeStampTest()
        {
            // TODO unit test for the property 'TimeStamp'
        }
        /// <summary>
        /// Test the property 'WorkflowIds'
        /// </summary>
        [Test]
        public void WorkflowIdsTest()
        {
            // TODO unit test for the property 'WorkflowIds'
        }

    }

}
