/* 
 * Orkes Conductor API Server
 *
 * Orkes Conductor API Server
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WorkflowScheduleExecutionModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WorkflowScheduleExecutionModelTests
    {
        // TODO uncomment below to declare an instance variable for WorkflowScheduleExecutionModel
        //private WorkflowScheduleExecutionModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WorkflowScheduleExecutionModel
            //instance = new WorkflowScheduleExecutionModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WorkflowScheduleExecutionModel
        /// </summary>
        [Test]
        public void WorkflowScheduleExecutionModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WorkflowScheduleExecutionModel
            //Assert.IsInstanceOfType<WorkflowScheduleExecutionModel> (instance, "variable 'instance' is a WorkflowScheduleExecutionModel");
        }


        /// <summary>
        /// Test the property 'ExecutionId'
        /// </summary>
        [Test]
        public void ExecutionIdTest()
        {
            // TODO unit test for the property 'ExecutionId'
        }
        /// <summary>
        /// Test the property 'ExecutionTime'
        /// </summary>
        [Test]
        public void ExecutionTimeTest()
        {
            // TODO unit test for the property 'ExecutionTime'
        }
        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Test]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }
        /// <summary>
        /// Test the property 'ScheduleName'
        /// </summary>
        [Test]
        public void ScheduleNameTest()
        {
            // TODO unit test for the property 'ScheduleName'
        }
        /// <summary>
        /// Test the property 'ScheduledTime'
        /// </summary>
        [Test]
        public void ScheduledTimeTest()
        {
            // TODO unit test for the property 'ScheduledTime'
        }
        /// <summary>
        /// Test the property 'StackTrace'
        /// </summary>
        [Test]
        public void StackTraceTest()
        {
            // TODO unit test for the property 'StackTrace'
        }
        /// <summary>
        /// Test the property 'StartWorkflowRequest'
        /// </summary>
        [Test]
        public void StartWorkflowRequestTest()
        {
            // TODO unit test for the property 'StartWorkflowRequest'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'WorkflowId'
        /// </summary>
        [Test]
        public void WorkflowIdTest()
        {
            // TODO unit test for the property 'WorkflowId'
        }
        /// <summary>
        /// Test the property 'WorkflowName'
        /// </summary>
        [Test]
        public void WorkflowNameTest()
        {
            // TODO unit test for the property 'WorkflowName'
        }

    }

}
