/* 
 * Orkes Conductor API Server
 *
 * Orkes Conductor API Server
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Workflow
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WorkflowTests
    {
        // TODO uncomment below to declare an instance variable for Workflow
        //private Workflow instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Workflow
            //instance = new Workflow();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Workflow
        /// </summary>
        [Test]
        public void WorkflowInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Workflow
            //Assert.IsInstanceOfType<Workflow> (instance, "variable 'instance' is a Workflow");
        }


        /// <summary>
        /// Test the property 'CorrelationId'
        /// </summary>
        [Test]
        public void CorrelationIdTest()
        {
            // TODO unit test for the property 'CorrelationId'
        }
        /// <summary>
        /// Test the property 'CreateTime'
        /// </summary>
        [Test]
        public void CreateTimeTest()
        {
            // TODO unit test for the property 'CreateTime'
        }
        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Test]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }
        /// <summary>
        /// Test the property 'EndTime'
        /// </summary>
        [Test]
        public void EndTimeTest()
        {
            // TODO unit test for the property 'EndTime'
        }
        /// <summary>
        /// Test the property '_Event'
        /// </summary>
        [Test]
        public void _EventTest()
        {
            // TODO unit test for the property '_Event'
        }
        /// <summary>
        /// Test the property 'ExternalInputPayloadStoragePath'
        /// </summary>
        [Test]
        public void ExternalInputPayloadStoragePathTest()
        {
            // TODO unit test for the property 'ExternalInputPayloadStoragePath'
        }
        /// <summary>
        /// Test the property 'ExternalOutputPayloadStoragePath'
        /// </summary>
        [Test]
        public void ExternalOutputPayloadStoragePathTest()
        {
            // TODO unit test for the property 'ExternalOutputPayloadStoragePath'
        }
        /// <summary>
        /// Test the property 'FailedReferenceTaskNames'
        /// </summary>
        [Test]
        public void FailedReferenceTaskNamesTest()
        {
            // TODO unit test for the property 'FailedReferenceTaskNames'
        }
        /// <summary>
        /// Test the property 'Input'
        /// </summary>
        [Test]
        public void InputTest()
        {
            // TODO unit test for the property 'Input'
        }
        /// <summary>
        /// Test the property 'LastRetriedTime'
        /// </summary>
        [Test]
        public void LastRetriedTimeTest()
        {
            // TODO unit test for the property 'LastRetriedTime'
        }
        /// <summary>
        /// Test the property 'Output'
        /// </summary>
        [Test]
        public void OutputTest()
        {
            // TODO unit test for the property 'Output'
        }
        /// <summary>
        /// Test the property 'OwnerApp'
        /// </summary>
        [Test]
        public void OwnerAppTest()
        {
            // TODO unit test for the property 'OwnerApp'
        }
        /// <summary>
        /// Test the property 'ParentWorkflowId'
        /// </summary>
        [Test]
        public void ParentWorkflowIdTest()
        {
            // TODO unit test for the property 'ParentWorkflowId'
        }
        /// <summary>
        /// Test the property 'ParentWorkflowTaskId'
        /// </summary>
        [Test]
        public void ParentWorkflowTaskIdTest()
        {
            // TODO unit test for the property 'ParentWorkflowTaskId'
        }
        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Test]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }
        /// <summary>
        /// Test the property 'ReRunFromWorkflowId'
        /// </summary>
        [Test]
        public void ReRunFromWorkflowIdTest()
        {
            // TODO unit test for the property 'ReRunFromWorkflowId'
        }
        /// <summary>
        /// Test the property 'ReasonForIncompletion'
        /// </summary>
        [Test]
        public void ReasonForIncompletionTest()
        {
            // TODO unit test for the property 'ReasonForIncompletion'
        }
        /// <summary>
        /// Test the property 'StartTime'
        /// </summary>
        [Test]
        public void StartTimeTest()
        {
            // TODO unit test for the property 'StartTime'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'TaskToDomain'
        /// </summary>
        [Test]
        public void TaskToDomainTest()
        {
            // TODO unit test for the property 'TaskToDomain'
        }
        /// <summary>
        /// Test the property 'Tasks'
        /// </summary>
        [Test]
        public void TasksTest()
        {
            // TODO unit test for the property 'Tasks'
        }
        /// <summary>
        /// Test the property 'UpdateTime'
        /// </summary>
        [Test]
        public void UpdateTimeTest()
        {
            // TODO unit test for the property 'UpdateTime'
        }
        /// <summary>
        /// Test the property 'UpdatedBy'
        /// </summary>
        [Test]
        public void UpdatedByTest()
        {
            // TODO unit test for the property 'UpdatedBy'
        }
        /// <summary>
        /// Test the property 'Variables'
        /// </summary>
        [Test]
        public void VariablesTest()
        {
            // TODO unit test for the property 'Variables'
        }
        /// <summary>
        /// Test the property 'WorkflowDefinition'
        /// </summary>
        [Test]
        public void WorkflowDefinitionTest()
        {
            // TODO unit test for the property 'WorkflowDefinition'
        }
        /// <summary>
        /// Test the property 'WorkflowId'
        /// </summary>
        [Test]
        public void WorkflowIdTest()
        {
            // TODO unit test for the property 'WorkflowId'
        }
        /// <summary>
        /// Test the property 'WorkflowName'
        /// </summary>
        [Test]
        public void WorkflowNameTest()
        {
            // TODO unit test for the property 'WorkflowName'
        }
        /// <summary>
        /// Test the property 'WorkflowVersion'
        /// </summary>
        [Test]
        public void WorkflowVersionTest()
        {
            // TODO unit test for the property 'WorkflowVersion'
        }

    }

}
