/* 
 * Orkes Conductor API Server
 *
 * Orkes Conductor API Server
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing IncomingWebhookResourceApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class IncomingWebhookResourceApiTests
    {
        private IncomingWebhookResourceApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new IncomingWebhookResourceApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of IncomingWebhookResourceApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' IncomingWebhookResourceApi
            //Assert.IsInstanceOfType(typeof(IncomingWebhookResourceApi), instance, "instance is a IncomingWebhookResourceApi");
        }

        /// <summary>
        /// Test HandleWebhook
        /// </summary>
        [Test]
        public void HandleWebhookTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string body = null;
            //string id = null;
            //var response = instance.HandleWebhook(body, id);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        /// <summary>
        /// Test HandleWebhook1
        /// </summary>
        [Test]
        public void HandleWebhook1Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //Dictionary<string, string> requestParams = null;
            //var response = instance.HandleWebhook1(id, requestParams);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
    }

}
