/* 
 * Orkes Conductor API Server
 *
 * Orkes Conductor API Server
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MigrationResourceApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class MigrationResourceApiTests
    {
        private MigrationResourceApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new MigrationResourceApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MigrationResourceApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' MigrationResourceApi
            //Assert.IsInstanceOfType(typeof(MigrationResourceApi), instance, "instance is a MigrationResourceApi");
        }

        /// <summary>
        /// Test MigrateIndex
        /// </summary>
        [Test]
        public void MigrateIndexTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.MigrateIndex();
            //Assert.IsInstanceOf<int?> (response, "response is int?");
        }
        /// <summary>
        /// Test MigrateMetadata
        /// </summary>
        [Test]
        public void MigrateMetadataTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.MigrateMetadata();
            
        }
        /// <summary>
        /// Test MigrateWorkflows
        /// </summary>
        [Test]
        public void MigrateWorkflowsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? batchSize = null;
            //long? startFromTimestamp = null;
            //var response = instance.MigrateWorkflows(batchSize, startFromTimestamp);
            //Assert.IsInstanceOf<Dictionary<string, Object>> (response, "response is Dictionary<string, Object>");
        }
    }

}
