/* 
 * Orkes Conductor API Server
 *
 * Orkes Conductor API Server
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing QueueAdminResourceApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class QueueAdminResourceApiTests
    {
        private QueueAdminResourceApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new QueueAdminResourceApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of QueueAdminResourceApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' QueueAdminResourceApi
            //Assert.IsInstanceOfType(typeof(QueueAdminResourceApi), instance, "instance is a QueueAdminResourceApi");
        }

        /// <summary>
        /// Test Names
        /// </summary>
        [Test]
        public void NamesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.Names();
            //Assert.IsInstanceOf<Dictionary<string, string>> (response, "response is Dictionary<string, string>");
        }
        /// <summary>
        /// Test Size1
        /// </summary>
        [Test]
        public void Size1Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.Size1();
            //Assert.IsInstanceOf<Dictionary<string, Dictionary<string, long?>>> (response, "response is Dictionary<string, Dictionary<string, long?>>");
        }
    }

}
