/*
 * Conductor API Server
 *
 * Conductor API Server
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Conductor.Client.Models
{
    /// <summary>
    /// WorkflowTask
    /// </summary>
    [DataContract(Name = "WorkflowTask")]
    public partial class WorkflowTask : IEquatable<WorkflowTask>, IValidatableObject
    {
        /// <summary>
        /// Defines WorkflowTaskType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum WorkflowTaskTypeEnum
        {
            /// <summary>
            /// Enum SIMPLE for value: SIMPLE
            /// </summary>
            [EnumMember(Value = "SIMPLE")]
            SIMPLE = 1,

            /// <summary>
            /// Enum DYNAMIC for value: DYNAMIC
            /// </summary>
            [EnumMember(Value = "DYNAMIC")]
            DYNAMIC = 2,

            /// <summary>
            /// Enum FORKJOIN for value: FORK_JOIN
            /// </summary>
            [EnumMember(Value = "FORK_JOIN")]
            FORKJOIN = 3,

            /// <summary>
            /// Enum FORKJOINDYNAMIC for value: FORK_JOIN_DYNAMIC
            /// </summary>
            [EnumMember(Value = "FORK_JOIN_DYNAMIC")]
            FORKJOINDYNAMIC = 4,

            /// <summary>
            /// Enum DECISION for value: DECISION
            /// </summary>
            [EnumMember(Value = "DECISION")]
            DECISION = 5,

            /// <summary>
            /// Enum SWITCH for value: SWITCH
            /// </summary>
            [EnumMember(Value = "SWITCH")]
            SWITCH = 6,

            /// <summary>
            /// Enum JOIN for value: JOIN
            /// </summary>
            [EnumMember(Value = "JOIN")]
            JOIN = 7,

            /// <summary>
            /// Enum DOWHILE for value: DO_WHILE
            /// </summary>
            [EnumMember(Value = "DO_WHILE")]
            DOWHILE = 8,

            /// <summary>
            /// Enum SUBWORKFLOW for value: SUB_WORKFLOW
            /// </summary>
            [EnumMember(Value = "SUB_WORKFLOW")]
            SUBWORKFLOW = 9,

            /// <summary>
            /// Enum EVENT for value: EVENT
            /// </summary>
            [EnumMember(Value = "EVENT")]
            EVENT = 10,

            /// <summary>
            /// Enum WAIT for value: WAIT
            /// </summary>
            [EnumMember(Value = "WAIT")]
            WAIT = 11,

            /// <summary>
            /// Enum USERDEFINED for value: USER_DEFINED
            /// </summary>
            [EnumMember(Value = "USER_DEFINED")]
            USERDEFINED = 12,

            /// <summary>
            /// Enum HTTP for value: HTTP
            /// </summary>
            [EnumMember(Value = "HTTP")]
            HTTP = 13,

            /// <summary>
            /// Enum LAMBDA for value: LAMBDA
            /// </summary>
            [EnumMember(Value = "LAMBDA")]
            LAMBDA = 14,

            /// <summary>
            /// Enum INLINE for value: INLINE
            /// </summary>
            [EnumMember(Value = "INLINE")]
            INLINE = 15,

            /// <summary>
            /// Enum EXCLUSIVEJOIN for value: EXCLUSIVE_JOIN
            /// </summary>
            [EnumMember(Value = "EXCLUSIVE_JOIN")]
            EXCLUSIVEJOIN = 16,

            /// <summary>
            /// Enum TERMINATE for value: TERMINATE
            /// </summary>
            [EnumMember(Value = "TERMINATE")]
            TERMINATE = 17,

            /// <summary>
            /// Enum KAFKAPUBLISH for value: KAFKA_PUBLISH
            /// </summary>
            [EnumMember(Value = "KAFKA_PUBLISH")]
            KAFKAPUBLISH = 18,

            /// <summary>
            /// Enum JSONJQTRANSFORM for value: JSON_JQ_TRANSFORM
            /// </summary>
            [EnumMember(Value = "JSON_JQ_TRANSFORM")]
            JSONJQTRANSFORM = 19,

            /// <summary>
            /// Enum SETVARIABLE for value: SET_VARIABLE
            /// </summary>
            [EnumMember(Value = "SET_VARIABLE")]
            SETVARIABLE = 20

        }


        /// <summary>
        /// Gets or Sets WorkflowTaskType
        /// </summary>
        [DataMember(Name = "workflowTaskType", EmitDefaultValue = false)]
        public WorkflowTaskTypeEnum? WorkflowTaskType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowTask" /> class.
        /// </summary>
        [JsonConstructor]
        protected WorkflowTask() { }

        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowTask" /> class.
        /// </summary>
        /// <param name="name">name (required).</param>
        /// <param name="taskReferenceName">taskReferenceName (required).</param>
        /// <param name="description">description.</param>
        /// <param name="inputParameters">inputParameters.</param>
        /// <param name="type">type.</param>
        /// <param name="dynamicTaskNameParam">dynamicTaskNameParam.</param>
        /// <param name="caseValueParam">caseValueParam.</param>
        /// <param name="caseExpression">caseExpression.</param>
        /// <param name="scriptExpression">scriptExpression.</param>
        /// <param name="decisionCases">decisionCases.</param>
        /// <param name="dynamicForkJoinTasksParam">dynamicForkJoinTasksParam.</param>
        /// <param name="dynamicForkTasksParam">dynamicForkTasksParam.</param>
        /// <param name="dynamicForkTasksInputParamName">dynamicForkTasksInputParamName.</param>
        /// <param name="defaultCase">defaultCase.</param>
        /// <param name="forkTasks">forkTasks.</param>
        /// <param name="startDelay">startDelay.</param>
        /// <param name="subWorkflowParam">subWorkflowParam.</param>
        /// <param name="joinOn">joinOn.</param>
        /// <param name="sink">sink.</param>
        /// <param name="optional">optional.</param>
        /// <param name="taskDefinition">taskDefinition.</param>
        /// <param name="rateLimited">rateLimited.</param>
        /// <param name="defaultExclusiveJoinTask">defaultExclusiveJoinTask.</param>
        /// <param name="asyncComplete">asyncComplete.</param>
        /// <param name="loopCondition">loopCondition.</param>
        /// <param name="loopOver">loopOver.</param>
        /// <param name="retryCount">retryCount.</param>
        /// <param name="evaluatorType">evaluatorType.</param>
        /// <param name="expression">expression.</param>
        /// <param name="workflowTaskType">workflowTaskType.</param>
        [Obsolete]
        public WorkflowTask(string name = default(string), string taskReferenceName = default(string), string description = default(string), Dictionary<string, Object> inputParameters = default(Dictionary<string, Object>), string type = default(string), string dynamicTaskNameParam = default(string), string caseValueParam = default(string), string caseExpression = default(string), string scriptExpression = default(string), Dictionary<string, List<WorkflowTask>> decisionCases = default(Dictionary<string, List<WorkflowTask>>), string dynamicForkJoinTasksParam = default(string), string dynamicForkTasksParam = default(string), string dynamicForkTasksInputParamName = default(string), List<WorkflowTask> defaultCase = default(List<WorkflowTask>), List<List<WorkflowTask>> forkTasks = default(List<List<WorkflowTask>>), int startDelay = default(int), SubWorkflowParams subWorkflowParam = default(SubWorkflowParams), List<string> joinOn = default(List<string>), string sink = default(string), bool optional = default(bool), TaskDef taskDefinition = default(TaskDef), bool rateLimited = default(bool), List<string> defaultExclusiveJoinTask = default(List<string>), bool asyncComplete = default(bool), string loopCondition = default(string), List<WorkflowTask> loopOver = default(List<WorkflowTask>), int retryCount = default(int), string evaluatorType = default(string), string expression = default(string), WorkflowTaskTypeEnum? workflowTaskType = default(WorkflowTaskTypeEnum?))
        {
            // to ensure "name" is required (not null)
            if (name == null) {
                throw new ArgumentNullException("name is a required property for WorkflowTask and cannot be null");
            }
            this.Name = name;
            // to ensure "taskReferenceName" is required (not null)
            if (taskReferenceName == null) {
                throw new ArgumentNullException("taskReferenceName is a required property for WorkflowTask and cannot be null");
            }
            this.TaskReferenceName = taskReferenceName;
            this.Description = description;
            this.InputParameters = inputParameters;
            this.Type = type;
            this.DynamicTaskNameParam = dynamicTaskNameParam;
            this.CaseValueParam = caseValueParam;
            this.CaseExpression = caseExpression;
            this.ScriptExpression = scriptExpression;
            this.DecisionCases = decisionCases;
            this.DynamicForkJoinTasksParam = dynamicForkJoinTasksParam;
            this.DynamicForkTasksParam = dynamicForkTasksParam;
            this.DynamicForkTasksInputParamName = dynamicForkTasksInputParamName;
            this.DefaultCase = defaultCase;
            this.ForkTasks = forkTasks;
            this.StartDelay = startDelay;
            this.SubWorkflowParam = subWorkflowParam;
            this.JoinOn = joinOn;
            this.Sink = sink;
            this.Optional = optional;
            this.TaskDefinition = taskDefinition;
            this.RateLimited = rateLimited;
            this.DefaultExclusiveJoinTask = defaultExclusiveJoinTask;
            this.AsyncComplete = asyncComplete;
            this.LoopCondition = loopCondition;
            this.LoopOver = loopOver;
            this.RetryCount = retryCount;
            this.EvaluatorType = evaluatorType;
            this.Expression = expression;
            this.WorkflowTaskType = workflowTaskType;
        }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets TaskReferenceName
        /// </summary>
        [DataMember(Name = "taskReferenceName", IsRequired = true, EmitDefaultValue = false)]
        public string TaskReferenceName { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets InputParameters
        /// </summary>
        [DataMember(Name = "inputParameters", EmitDefaultValue = false)]
        public Dictionary<string, Object> InputParameters { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets DynamicTaskNameParam
        /// </summary>
        [DataMember(Name = "dynamicTaskNameParam", EmitDefaultValue = false)]
        public string DynamicTaskNameParam { get; set; }

        /// <summary>
        /// Gets or Sets CaseValueParam
        /// </summary>
        [DataMember(Name = "caseValueParam", EmitDefaultValue = false)]
        [Obsolete]
        public string CaseValueParam { get; set; }

        /// <summary>
        /// Gets or Sets CaseExpression
        /// </summary>
        [DataMember(Name = "caseExpression", EmitDefaultValue = false)]
        [Obsolete]
        public string CaseExpression { get; set; }

        /// <summary>
        /// Gets or Sets ScriptExpression
        /// </summary>
        [DataMember(Name = "scriptExpression", EmitDefaultValue = false)]
        public string ScriptExpression { get; set; }

        /// <summary>
        /// Gets or Sets DecisionCases
        /// </summary>
        [DataMember(Name = "decisionCases", EmitDefaultValue = false)]
        public Dictionary<string, List<WorkflowTask>> DecisionCases { get; set; }

        /// <summary>
        /// Gets or Sets DynamicForkJoinTasksParam
        /// </summary>
        [DataMember(Name = "dynamicForkJoinTasksParam", EmitDefaultValue = false)]
        [Obsolete]
        public string DynamicForkJoinTasksParam { get; set; }

        /// <summary>
        /// Gets or Sets DynamicForkTasksParam
        /// </summary>
        [DataMember(Name = "dynamicForkTasksParam", EmitDefaultValue = false)]
        public string DynamicForkTasksParam { get; set; }

        /// <summary>
        /// Gets or Sets DynamicForkTasksInputParamName
        /// </summary>
        [DataMember(Name = "dynamicForkTasksInputParamName", EmitDefaultValue = false)]
        public string DynamicForkTasksInputParamName { get; set; }

        /// <summary>
        /// Gets or Sets DefaultCase
        /// </summary>
        [DataMember(Name = "defaultCase", EmitDefaultValue = false)]
        public List<WorkflowTask> DefaultCase { get; set; }

        /// <summary>
        /// Gets or Sets ForkTasks
        /// </summary>
        [DataMember(Name = "forkTasks", EmitDefaultValue = false)]
        public List<List<WorkflowTask>> ForkTasks { get; set; }

        /// <summary>
        /// Gets or Sets StartDelay
        /// </summary>
        [DataMember(Name = "startDelay", EmitDefaultValue = false)]
        public int StartDelay { get; set; }

        /// <summary>
        /// Gets or Sets SubWorkflowParam
        /// </summary>
        [DataMember(Name = "subWorkflowParam", EmitDefaultValue = false)]
        public SubWorkflowParams SubWorkflowParam { get; set; }

        /// <summary>
        /// Gets or Sets JoinOn
        /// </summary>
        [DataMember(Name = "joinOn", EmitDefaultValue = false)]
        public List<string> JoinOn { get; set; }

        /// <summary>
        /// Gets or Sets Sink
        /// </summary>
        [DataMember(Name = "sink", EmitDefaultValue = false)]
        public string Sink { get; set; }

        /// <summary>
        /// Gets or Sets Optional
        /// </summary>
        [DataMember(Name = "optional", EmitDefaultValue = true)]
        public bool Optional { get; set; }

        /// <summary>
        /// Gets or Sets TaskDefinition
        /// </summary>
        [DataMember(Name = "taskDefinition", EmitDefaultValue = false)]
        public TaskDef TaskDefinition { get; set; }

        /// <summary>
        /// Gets or Sets RateLimited
        /// </summary>
        [DataMember(Name = "rateLimited", EmitDefaultValue = true)]
        public bool RateLimited { get; set; }

        /// <summary>
        /// Gets or Sets DefaultExclusiveJoinTask
        /// </summary>
        [DataMember(Name = "defaultExclusiveJoinTask", EmitDefaultValue = false)]
        public List<string> DefaultExclusiveJoinTask { get; set; }

        /// <summary>
        /// Gets or Sets AsyncComplete
        /// </summary>
        [DataMember(Name = "asyncComplete", EmitDefaultValue = true)]
        public bool AsyncComplete { get; set; }

        /// <summary>
        /// Gets or Sets LoopCondition
        /// </summary>
        [DataMember(Name = "loopCondition", EmitDefaultValue = false)]
        public string LoopCondition { get; set; }

        /// <summary>
        /// Gets or Sets LoopOver
        /// </summary>
        [DataMember(Name = "loopOver", EmitDefaultValue = false)]
        public List<WorkflowTask> LoopOver { get; set; }

        /// <summary>
        /// Gets or Sets RetryCount
        /// </summary>
        [DataMember(Name = "retryCount", EmitDefaultValue = false)]
        public int RetryCount { get; set; }

        /// <summary>
        /// Gets or Sets EvaluatorType
        /// </summary>
        [DataMember(Name = "evaluatorType", EmitDefaultValue = false)]
        public string EvaluatorType { get; set; }

        /// <summary>
        /// Gets or Sets Expression
        /// </summary>
        [DataMember(Name = "expression", EmitDefaultValue = false)]
        public string Expression { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        [Obsolete]
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WorkflowTask {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  TaskReferenceName: ").Append(TaskReferenceName).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  InputParameters: ").Append(InputParameters).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  DynamicTaskNameParam: ").Append(DynamicTaskNameParam).Append("\n");
            sb.Append("  CaseValueParam: ").Append(CaseValueParam).Append("\n");
            sb.Append("  CaseExpression: ").Append(CaseExpression).Append("\n");
            sb.Append("  ScriptExpression: ").Append(ScriptExpression).Append("\n");
            sb.Append("  DecisionCases: ").Append(DecisionCases).Append("\n");
            sb.Append("  DynamicForkJoinTasksParam: ").Append(DynamicForkJoinTasksParam).Append("\n");
            sb.Append("  DynamicForkTasksParam: ").Append(DynamicForkTasksParam).Append("\n");
            sb.Append("  DynamicForkTasksInputParamName: ").Append(DynamicForkTasksInputParamName).Append("\n");
            sb.Append("  DefaultCase: ").Append(DefaultCase).Append("\n");
            sb.Append("  ForkTasks: ").Append(ForkTasks).Append("\n");
            sb.Append("  StartDelay: ").Append(StartDelay).Append("\n");
            sb.Append("  SubWorkflowParam: ").Append(SubWorkflowParam).Append("\n");
            sb.Append("  JoinOn: ").Append(JoinOn).Append("\n");
            sb.Append("  Sink: ").Append(Sink).Append("\n");
            sb.Append("  Optional: ").Append(Optional).Append("\n");
            sb.Append("  TaskDefinition: ").Append(TaskDefinition).Append("\n");
            sb.Append("  RateLimited: ").Append(RateLimited).Append("\n");
            sb.Append("  DefaultExclusiveJoinTask: ").Append(DefaultExclusiveJoinTask).Append("\n");
            sb.Append("  AsyncComplete: ").Append(AsyncComplete).Append("\n");
            sb.Append("  LoopCondition: ").Append(LoopCondition).Append("\n");
            sb.Append("  LoopOver: ").Append(LoopOver).Append("\n");
            sb.Append("  RetryCount: ").Append(RetryCount).Append("\n");
            sb.Append("  EvaluatorType: ").Append(EvaluatorType).Append("\n");
            sb.Append("  Expression: ").Append(Expression).Append("\n");
            sb.Append("  WorkflowTaskType: ").Append(WorkflowTaskType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        [Obsolete]
        public override bool Equals(object input)
        {
            return this.Equals(input as WorkflowTask);
        }

        /// <summary>
        /// Returns true if WorkflowTask instances are equal
        /// </summary>
        /// <param name="input">Instance of WorkflowTask to be compared</param>
        /// <returns>Boolean</returns>
        [Obsolete]
        public bool Equals(WorkflowTask input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.TaskReferenceName == input.TaskReferenceName ||
                    (this.TaskReferenceName != null &&
                    this.TaskReferenceName.Equals(input.TaskReferenceName))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.InputParameters == input.InputParameters ||
                    this.InputParameters != null &&
                    input.InputParameters != null &&
                    this.InputParameters.SequenceEqual(input.InputParameters)
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.DynamicTaskNameParam == input.DynamicTaskNameParam ||
                    (this.DynamicTaskNameParam != null &&
                    this.DynamicTaskNameParam.Equals(input.DynamicTaskNameParam))
                ) && 
                (
                    this.CaseValueParam == input.CaseValueParam ||
                    (this.CaseValueParam != null &&
                    this.CaseValueParam.Equals(input.CaseValueParam))
                ) && 
                (
                    this.CaseExpression == input.CaseExpression ||
                    (this.CaseExpression != null &&
                    this.CaseExpression.Equals(input.CaseExpression))
                ) && 
                (
                    this.ScriptExpression == input.ScriptExpression ||
                    (this.ScriptExpression != null &&
                    this.ScriptExpression.Equals(input.ScriptExpression))
                ) && 
                (
                    this.DecisionCases == input.DecisionCases ||
                    this.DecisionCases != null &&
                    input.DecisionCases != null &&
                    this.DecisionCases.SequenceEqual(input.DecisionCases)
                ) && 
                (
                    this.DynamicForkJoinTasksParam == input.DynamicForkJoinTasksParam ||
                    (this.DynamicForkJoinTasksParam != null &&
                    this.DynamicForkJoinTasksParam.Equals(input.DynamicForkJoinTasksParam))
                ) && 
                (
                    this.DynamicForkTasksParam == input.DynamicForkTasksParam ||
                    (this.DynamicForkTasksParam != null &&
                    this.DynamicForkTasksParam.Equals(input.DynamicForkTasksParam))
                ) && 
                (
                    this.DynamicForkTasksInputParamName == input.DynamicForkTasksInputParamName ||
                    (this.DynamicForkTasksInputParamName != null &&
                    this.DynamicForkTasksInputParamName.Equals(input.DynamicForkTasksInputParamName))
                ) && 
                (
                    this.DefaultCase == input.DefaultCase ||
                    this.DefaultCase != null &&
                    input.DefaultCase != null &&
                    this.DefaultCase.SequenceEqual(input.DefaultCase)
                ) && 
                (
                    this.ForkTasks == input.ForkTasks ||
                    this.ForkTasks != null &&
                    input.ForkTasks != null &&
                    this.ForkTasks.SequenceEqual(input.ForkTasks)
                ) && 
                (
                    this.StartDelay == input.StartDelay ||
                    this.StartDelay.Equals(input.StartDelay)
                ) && 
                (
                    this.SubWorkflowParam == input.SubWorkflowParam ||
                    (this.SubWorkflowParam != null &&
                    this.SubWorkflowParam.Equals(input.SubWorkflowParam))
                ) && 
                (
                    this.JoinOn == input.JoinOn ||
                    this.JoinOn != null &&
                    input.JoinOn != null &&
                    this.JoinOn.SequenceEqual(input.JoinOn)
                ) && 
                (
                    this.Sink == input.Sink ||
                    (this.Sink != null &&
                    this.Sink.Equals(input.Sink))
                ) && 
                (
                    this.Optional == input.Optional ||
                    this.Optional.Equals(input.Optional)
                ) && 
                (
                    this.TaskDefinition == input.TaskDefinition ||
                    (this.TaskDefinition != null &&
                    this.TaskDefinition.Equals(input.TaskDefinition))
                ) && 
                (
                    this.RateLimited == input.RateLimited ||
                    this.RateLimited.Equals(input.RateLimited)
                ) && 
                (
                    this.DefaultExclusiveJoinTask == input.DefaultExclusiveJoinTask ||
                    this.DefaultExclusiveJoinTask != null &&
                    input.DefaultExclusiveJoinTask != null &&
                    this.DefaultExclusiveJoinTask.SequenceEqual(input.DefaultExclusiveJoinTask)
                ) && 
                (
                    this.AsyncComplete == input.AsyncComplete ||
                    this.AsyncComplete.Equals(input.AsyncComplete)
                ) && 
                (
                    this.LoopCondition == input.LoopCondition ||
                    (this.LoopCondition != null &&
                    this.LoopCondition.Equals(input.LoopCondition))
                ) && 
                (
                    this.LoopOver == input.LoopOver ||
                    this.LoopOver != null &&
                    input.LoopOver != null &&
                    this.LoopOver.SequenceEqual(input.LoopOver)
                ) && 
                (
                    this.RetryCount == input.RetryCount ||
                    this.RetryCount.Equals(input.RetryCount)
                ) && 
                (
                    this.EvaluatorType == input.EvaluatorType ||
                    (this.EvaluatorType != null &&
                    this.EvaluatorType.Equals(input.EvaluatorType))
                ) && 
                (
                    this.Expression == input.Expression ||
                    (this.Expression != null &&
                    this.Expression.Equals(input.Expression))
                ) && 
                (
                    this.WorkflowTaskType == input.WorkflowTaskType ||
                    this.WorkflowTaskType.Equals(input.WorkflowTaskType)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        [Obsolete]
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.TaskReferenceName != null)
                {
                    hashCode = (hashCode * 59) + this.TaskReferenceName.GetHashCode();
                }
                if (this.Description != null)
                {
                    hashCode = (hashCode * 59) + this.Description.GetHashCode();
                }
                if (this.InputParameters != null)
                {
                    hashCode = (hashCode * 59) + this.InputParameters.GetHashCode();
                }
                if (this.Type != null)
                {
                    hashCode = (hashCode * 59) + this.Type.GetHashCode();
                }
                if (this.DynamicTaskNameParam != null)
                {
                    hashCode = (hashCode * 59) + this.DynamicTaskNameParam.GetHashCode();
                }
                if (this.CaseValueParam != null)
                {
                    hashCode = (hashCode * 59) + this.CaseValueParam.GetHashCode();
                }
                if (this.CaseExpression != null)
                {
                    hashCode = (hashCode * 59) + this.CaseExpression.GetHashCode();
                }
                if (this.ScriptExpression != null)
                {
                    hashCode = (hashCode * 59) + this.ScriptExpression.GetHashCode();
                }
                if (this.DecisionCases != null)
                {
                    hashCode = (hashCode * 59) + this.DecisionCases.GetHashCode();
                }
                if (this.DynamicForkJoinTasksParam != null)
                {
                    hashCode = (hashCode * 59) + this.DynamicForkJoinTasksParam.GetHashCode();
                }
                if (this.DynamicForkTasksParam != null)
                {
                    hashCode = (hashCode * 59) + this.DynamicForkTasksParam.GetHashCode();
                }
                if (this.DynamicForkTasksInputParamName != null)
                {
                    hashCode = (hashCode * 59) + this.DynamicForkTasksInputParamName.GetHashCode();
                }
                if (this.DefaultCase != null)
                {
                    hashCode = (hashCode * 59) + this.DefaultCase.GetHashCode();
                }
                if (this.ForkTasks != null)
                {
                    hashCode = (hashCode * 59) + this.ForkTasks.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.StartDelay.GetHashCode();
                if (this.SubWorkflowParam != null)
                {
                    hashCode = (hashCode * 59) + this.SubWorkflowParam.GetHashCode();
                }
                if (this.JoinOn != null)
                {
                    hashCode = (hashCode * 59) + this.JoinOn.GetHashCode();
                }
                if (this.Sink != null)
                {
                    hashCode = (hashCode * 59) + this.Sink.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Optional.GetHashCode();
                if (this.TaskDefinition != null)
                {
                    hashCode = (hashCode * 59) + this.TaskDefinition.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.RateLimited.GetHashCode();
                if (this.DefaultExclusiveJoinTask != null)
                {
                    hashCode = (hashCode * 59) + this.DefaultExclusiveJoinTask.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.AsyncComplete.GetHashCode();
                if (this.LoopCondition != null)
                {
                    hashCode = (hashCode * 59) + this.LoopCondition.GetHashCode();
                }
                if (this.LoopOver != null)
                {
                    hashCode = (hashCode * 59) + this.LoopOver.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.RetryCount.GetHashCode();
                if (this.EvaluatorType != null)
                {
                    hashCode = (hashCode * 59) + this.EvaluatorType.GetHashCode();
                }
                if (this.Expression != null)
                {
                    hashCode = (hashCode * 59) + this.Expression.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.WorkflowTaskType.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
